### ISSUE TITLE
Separate validation and moving file to validated folder

### ISSUE THREAD

**Issue by adarshk7** [fastmonkeys/pontus#12]
Currently the validation (as in validating the file data) and validating (as in moving file to validated directory) are done under the same method.

In certain cases this can be problematic, eg. if for some reason some error caused file to be not saved in database (like invalid form submission due to some other reason), the file is still moved to validated folder and the form data still has the unvalidated key and that will not be found when the form is submitted with correct data causing another error.

**Comment by tvuotila** [comment]
Fixed in version 2.1.0
See https://github.com/fastmonkeys/pontus/commit/b5d7747b420c9fe28d0450183a00b45fa14e4fb1 for details.
